apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    requests.storage: "20Gi"
    limits.cpu: "6"
    limits.memory: "16Gi"
