apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  #namespace: project-quota
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "6i"
    limits.memory: "16Gi"
    limits.ephemeral-storage: "20Gi"
  scopes:
  - Terminating
