apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  generation: 1
  labels:
    machine.openshift.io/cluster-api-cluster: cluster4-e1a0-fkmkd
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: infra-1a
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster4-e1a0-fkmkd
      machine.openshift.io/cluster-api-machineset: infra-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: cluster4-e1a0-fkmkd
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: infra-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          infra: infra
      providerSpec:
        value:
          ami:
            id: ami-0320b7e30d4871a30
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster4-e1a0-fkmkd-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster4-e1a0-fkmkd-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster4-e1a0-fkmkd-private-us-east-2a
          tags:
          - name: kubernetes.io/cluster/cluster4-e1a0-fkmkd
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""
